# Generated by Django 3.1.7 on 2021-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210707_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amplifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Floodlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FluorescentTube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HandDryer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photocopier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_used', models.PositiveSmallIntegerField(max_length=200)),
                ('daily_cost', models.PositiveSmallIntegerField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='GuestUser',
        ),
    ]
