# Generated by Django 3.1.7 on 2021-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211219_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplifier',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='amplifier',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='computers',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='computers',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='floodlight',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='floodlight',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fluorescenttube',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fluorescenttube',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='handdryer',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='handdryer',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photocopier',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='photocopier',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='printer',
            name='daily_cost',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='printer',
            name='hours_used',
            field=models.PositiveBigIntegerField(max_length=200),
        ),
    ]
